name: 🧠 Update README (Pinned Repos + Timestamp)

on:
  schedule:
    - cron: "0 0 * * *" # ежедневно
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get pinned repositories
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo '🔗 Fetching pinned repositories via GraphQL...'

          curl -s -H "Authorization: bearer $GH_TOKEN" -X POST -d '{"query":"query { user(login: \"Atambek07\") { pinnedItems(first: 6, types: REPOSITORY) { nodes { ... on Repository { name url description }}}}}"}' https://api.github.com/graphql \
          | jq -r '.data.user.pinnedItems.nodes[] | "- [\(.name)](\(.url)) — \(.description // "No description")"' > featured.tmp

      - name: Update README
        run: |
          awk '
            /<!-- FEATURED_REPOS:START -->/ {print; system("cat featured.tmp"); skip=1; next}
            /<!-- FEATURED_REPOS:END -->/ {skip=0}
            skip==0 {print}
          ' README.md > README.tmp

          DATE=$(date -u "+%Y-%m-%d")
          sed -i "s|📅 Last updated: .*|📅 Last updated: ${DATE}|" README.tmp

          mv README.tmp README.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📌 Update pinned repos & date"
          git push

      - name: Cleanup
        run: rm -f featured.tmp
